### PR TITLE
Fixed Pty.Net project properties

### PR DESCRIPTION
**Pull request by javierdlg**
Properties required to publish on nuget.org

### CODE REVIEW

**Review by DHowett — COMMENTED** [review]
(Publishing this officially on nuget.org suggests a level of support that you may not be willing to give it. Is that the plan?)

**Review by milopezc — APPROVED** [review]

**Comment by javierdlg** [comment]
> (Publishing this officially on nuget.org suggests a level of support that you may not be willing to give it. Is that the plan?)

What level of support would be required? I'd like to publish this on NuGet since it's an OOS project and it's hard to compile without building the dependencies first.

**Comment by DHowett** [comment]
(And if I had to rephrase, it would be: My team is not willing to support OpenConsole.exe distributed via NuGet today, so the burden will fall to you :))

**Comment by javierdlg** [comment]
Lets deck this for the next terminal sync-up so that we understand the situation better.

**Pull request closed without merging**
